# Generated by Django 5.2.10 on 2026-01-19 23:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.FloatField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING')),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.wallet', to_field='wallet_id')),
            ],
        ),
        migrations.CreateModel(
            name='WalletLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.FloatField()),
                ('daily_limit_used', models.FloatField()),
                ('monthly_limit', models.FloatField()),
                ('monthly_limit_used', models.FloatField()),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_limits', to='app.wallet', to_field='wallet_id')),
            ],
        ),
    ]
