# Generated by Django 5.2.10 on 2026-01-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletlogs',
            name='event',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
