# Generated by Django 5.2.10 on 2026-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wallet_balance_walletlogs_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletlogs',
            name='event',
        ),
        migrations.AddField(
            model_name='walletlogs',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
